### PR TITLE
An initial dive into interactions (closes #40 , closes #42)

### LINKED ISSUE #40: discord.py is back under development
We need to assess whether or not it is feasible to move back to Discord.py, what needs to be changed (if anything), and when we should consider implementing features like slash commands (my current thoughts on this are to run slash commands alongside the classic commands, e.g. I suspect we will have great difficulty implementing some of the more "creative" features (like the custom command actions) using slash commands, and I also think it will be helpful to at least have a transition period.

### LINKED ISSUE #42: Discord buttons could be used on `EmbedPages`
As the title says, embed pages used for configurations and QOTDs can be migrated to use [message components](https://discord.com/developers/docs/interactions/message-components) that are present in the most recent versions of discord.py.

If completed, the `temp_utils_cog` containing reaction handlers for `EmbedPages` can be removed, I think, solving that problem too!

### PR DESCRIPTION
**Pull request by raven0034**
### What are the changes on the surface?

- All classic commands (where possible) now have a slash command equivalent - the classic commands have been retained in all cases. Nothing has yet been done with regards to the `actions` cog, which remains as classic commands only.

- The `EmbedPages` now use proper buttons rather than reactions like before.

### What is the rationale for these changes?

- From a user point of view, slash commands seem much more intuitive to use, with usage help information being made available at the point of usage, and where it has been applied, the types of data expected for each command argument (including having argument names presented to the user - which _encourages_ us to come up with names that makes sense and convey their usage well to the users).

- If, at any point, someone makes use of the source of this bot for _their_ hosting, the intention is that they are able to wholly make use of the functionality of the bot in a case where a message content intent is refused (you can read the message content intent FAQ [here](https://support-dev.discord.com/hc/en-us/articles/4404772028055-Message-Content-Privileged-Intent-FAQ)).

### What are the changes under the surface?

- Python version has been bumped to `3.10.5`

- One thing that I quickly picked up on when starting this task was the fact that most of the process behind each command is still fundamentally the same when implementing the classic commands using slash commands. However, keeping all of this within one file for each cog felt overly cluttered and not single purpose (this would have been evident with the `role` cog which would have been over 1000 lines without breaking it down).
     - As a result, each command is set up as follows: a command method, a slash command method, and a handler method which handles both of them.
     
     - The commands are still registered within their cogs, for example `userinfo` and `userinfo_slash` are still registered within the `member` guild, and the `userinfo` handler is within the `member_handlers` file.

- In an ideal world we would like implementations to be consistent however this has been a slight pain given there are numerous differences in the data provided by the API by message-issued commands ([Discord API docs](https://discord.com/developers/docs/resources/channel#message-object), [discord.py Context docs](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html?highlight=context#discord.ext.commands.Context)) and slash commands ([Discord API docs](https://discord.com/developers/docs/interactions/receiving-and-responding) [discord.py Interaction docs](https://discordpy.readthedocs.io/en/latest/interactions/api.html?highlight=interaction#discord.Interaction)).
    - This has meant that, for example `ctx.author` cannot be used in contexts where a `discord.Interaction` is being used (note that `ctx` now refers to either a classic `Context` or `Interaction` object), leading to checks for `ctx.user` to be used, either directly or to fetch a member object (which was needed in cases where member-only properties needed to be accessed like activities).

    - Where there is an `Interaction`, `ctx.client` has been used in place of `ctx.bot`

- Decorators for checking relevant permissions have all been adapted to have a slash command equivalent.

- Where a classic command group name could be used as a command as well as encompassing the command group, a suitable alternative has been chosen for the slash commands (for example `config` has an equivalent called `config view`). This is because, at the time of writing, Discord does not have support for this type of slash command yet.

- Type hints have been updated to accommodate for `discord.Interaction` where appropriate, and some of the new slash commands make use of Discord's type help (conveyed to it via type hints which d.py interprets), to encourage more simple use of some of the commands (and to reduce the potential burden on the bot of dealing with unintended inputs), as well as descriptions of the arguments through `app_commands.describe` ([docs](https://discordpy.readthedocs.io/en/latest/interactions/api.html?highlight=describe#discord.app_commands.describe))

- Slash commands (aka AppCommands internally) are registered through a CommandTree (which is then synced to notify Discord of changes - although it appears doing this globally is heavily rate-limited). Some extra handling was required to appropriately deal with commands being issued where the author did not have suitable permissions, hence an `AdamTree` class with a custom error handling system has been implemented.

- Every interaction must be responded to using the appropriate methods else the interaction is considered to have failed. Therefore a lot of the command handlers have been adapted to ensure that this occurs. In the process I decided to shift more of the responses over to using `DefaultEmbedResponses`, which has also been adapted to allow for responding to interactions, in order to tidy some of these adaptations up.

- The `temp_utils_cog` has been retired.

- Note that the methods used for detecting context types allow for subclassing so some of the features the `actions` cog relies upon are not broken.

### Things that could be pursued in the future:
 - Add a more intuitive help page potentially using some of the new buttons (taking inspiration from something like the Last.FM bots wouldn't be a bad idea).
 
 -  Adding the ability to support ephermal messages for some things (e.g. I had an idea of making reminders optionally private where they have to be sent in the channel they were created in because of DMs being closed)

- Could potentially make use of forms for some things

- Whatever else we think of ;)

### CODE REVIEW

**Comment by adampy** [comment]
Hey, I'm not currently in the UK and don't have a desktop to easily view all changes and I will review them when I get a chance. What is the `AdamTree` used for in terms of changes to commands?

**Comment by raven0034** [comment]
image

Here's an explanation of what the `CommandTree` is for (from the discord.py server). In this case `AdamTree` is basically an extension of the implementation found in `discord.app_commands.tree.CommandTree` so that some custom error handling can be done (specifically in `on_error` for stuff like `MissingStaffSlashError`). [Here's](https://discordpy.readthedocs.io/en/latest/interactions/api.html?highlight=tree#discord.app_commands.CommandTree.on_error) the docs link for what it's primarily for.

Just as I'm writing this I've just spotted a minor bug that I need to go back and fix 😅

**Review by adampy — APPROVED** [review]
I mostly went through each file learning about the use of handlers and how they're used as the bridge between functionality and both normal commands and slash commands. Changes overall LGTM. Have the changes been tested on a bot e.g. test bot or live Adam-Bot? @monkeyboy2805

**Comment by raven0034** [comment]
I have done a fair bit of testing on my test bot and I am happy that everything is working as intended as of so far.

**Comment by raven0034** [comment]
easterblessings-verstappen

**Pull request merged**
