### PR TITLE
Format time for discord's presentation in uptime session command

### PR DESCRIPTION
**Pull request by itzmk21**
[Looks](https://nextcord.readthedocs.io/en/latest/api.html#utility-functions) cool lol

### CODE REVIEW

**Comment by raven0034** [comment]
**_Please test your code before making a pull request._**

### Issue

```
datetime.fromtimestamp(seconds)
```

This part of your code gives you the datetime object of the beginning of POSIX time offset by the number of seconds as detailed in the Python [fromtimestamps documentation](https://docs.python.org/3/library/datetime.html#datetime.date.fromtimestamp), which results in weird thing like a datetime object from 1970 after the bot having an uptime for 100 seconds as demonstrated [here](https://cdn.discordapp.com/attachments/809791208884142140/941880407333429268/unknown.png) which in itself is probably not intended.

Furthermore this doesn't work when using `format_dt` as it fails to make a timestamp out of datetime objects that are so close to the start of POSIX time, as demonstrated [here](https://cdn.discordapp.com/attachments/809791208884142140/941880949593997382/unknown.png) and [on the bot itself](https://cdn.discordapp.com/attachments/809791208884142140/941881220193734686/unknown.png). `timestamp`'s use can also be found in the library source [here](https://github.com/Pycord-Development/pycord/blob/1198c2ae5a17b2b6f6325867d52efdbdeded61b7/discord/utils.py#L1047).

What we have done throughout the bot when needing time offsets is use `datetime.timedelta`, the documentation for which is [here](https://docs.python.org/3/library/datetime.html#datetime.timedelta).

Hope that helps ;)

**Comment by itzmk21** [comment]
@monkeyboy2805 woops my bad. Fixed.

```diff
- date = datetime.fromtimestamp(seconds)
+ date = datetime.fromtimestamp(self.bot.start_time)
```

**Comment by raven0034** [comment]
Looks fine at first glance, I'll properly review it for you later.

**Review by adampy — APPROVED** [review]
Hey, thanks for the PR. LGTM 👍 

@monkeyboy2805 do you agree?

**Comment by adampy** [comment]
> Hey, thanks for the PR. LGTM 👍

@monkeyboy2805 do you agree?

**Comment by raven0034** [comment]
lgtm too, probably best to squash merge so it's in one commit rather than 4 for the same thing :P

**Review by raven0034 — APPROVED** [review]

**Pull request merged**
