### PR TITLE
New `EmbedPages` with interactions

### LINKED ISSUE #42: Discord buttons could be used on `EmbedPages`
As the title says, embed pages used for configurations and QOTDs can be migrated to use [message components](https://discord.com/developers/docs/interactions/message-components) that are present in the most recent versions of discord.py.

If completed, the `temp_utils_cog` containing reaction handlers for `EmbedPages` can be removed, I think, solving that problem too!

### PR DESCRIPTION
**Pull request by adampy**
As the title says, fixes #42. Still yet to remove the `temp_utils_cog` at this point but will do shortly.

### CODE REVIEW

**Comment by adampy** [comment]
@monkeyboy2805 I'm unsure of a nice way to get the `EmbedPages` into the bot without the use of a cog that exists for the sole purpose of hooking it into the bot. At the moment this is done through the `temp_utils_cog`, and I'm not too sure on how to create a new cog (in terms of the config file needed). If you could help with that would be great :)

Otherwise, the `EmbedPages` have been moved out and are in a new file completely. The only thing inside of `temp_utils_cog` is handlers to prevent the bots from doing commands - do you agree that it could be moved out into `adambot.py`? If so, I can get on doing that too.

**Comment by raven0034** [comment]
Will have a look properly tomorrow - I should probably write some documentation on the configs stuff at some point too. Not 100% sure on my reasoning behind creating the temporary utils cog initially, if it's just handlers it does seem that they could be moved out of there (unless they belong to some specific features in which case ideally they should be paired up with some cog).

I've been meaning to look at utils as a whole, whilst I think it's a nice concept in terms of containing all the "miscellaneous" stuff the bot can make use of it could do with some tidying up at some point

**Comment by adampy** [comment]
> Will have a look properly tomorrow

No rush, just whenever you get a free moment 👍 

> if it's just handlers it does seem that they could be moved out of there

Yup, the handler to ensure bots do not invoke commands is not necessarily linked to anything, I will move that out later too.

**Comment by adampy** [comment]
Now the temporary cog has been removed, this is all I wish to change for this issue and PR. Ready to merge when you are 👍

**Review by raven0034 — APPROVED** [review]

**Pull request merged**
